# Generated by Django 4.2.7 on 2026-04-30 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clear_old_descriptions(apps, schema_editor):
    """Set all existing plain-text descriptions to a valid JSON empty object
    so the column can be safely cast to JSONB."""
    schema_editor.execute("UPDATE tasks_task SET description = '{}'")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_old_descriptions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
